name: danielistesting
favicon: null
layout_spectrum: 0.50013
typography_spectrum: 0.55715
title: 'Violet Flame Studios '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000001'
    - '#0000f3'
    - '#bb6dab'
    - '#591a9a'
    - '#4700fe'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
