name: danielistesting
favicon: null
layout_spectrum: 0.26473
typography_spectrum: 0.3142
title: Rousing Flow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#080405'
    - '#d96b3c'
    - '#933612'
    - '#fa191f'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
