typography_spectrum: 0.3142
color:
  brandColors:
    - '#ffffff'
    - '#080405'
    - '#d96b3c'
    - '#933612'
    - '#fa191f'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26473
analytics:
  google: null
  facebook: null
  twitter: null
name: danielistesting
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Get "Play Music"
    id: e90f55a3-4b00-42e4-a42a-dc0edcdd904b
    type: content
favicon: null
title: Rousing Flow
purpose: []
