name: danielistesting
favicon: null
layout_spectrum: 0.50177
typography_spectrum: 0.8688843459822237
title: 'Grid test '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.13654039124958217
  lightness: 0.1581034294795245
  saturation: 0.9320195035543293
  rhythmicContrast: 0.6049861141946167
purpose: []
