name: danielistesting
favicon: null
layout_spectrum: 0.5067
typography_spectrum: 0.55715
title: "Dan's test lab "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343434'
    - '#fc5c5f'
    - '#fffcfb'
    - '#f3ba96'
    - '#fb0416'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
