name: danielistesting
favicon: null
layout_spectrum: 0.50177
typography_spectrum: 0.55059
title: 'Grid test '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#080405'
    - '#d96b3c'
    - '#933612'
    - '#fa191f'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
