name: danielistesting
favicon: null
layout_spectrum: 0.74224
typography_spectrum: 0.82638
title: "Dan's test lab "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000029'
    - '#6f7376'
    - '#c9c4ca'
    - '#feedde'
    - '#584133'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
